name: "[Dispatch] Release"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch를 입력해주세요(master와 release-x.y.z만 허용)'
        required: true
        default: 'master'
      version:
        description: 'version을 입력해주세요(x.y.z)'
        required: true
        default: '1.0.0'

env:
  BRANCH: ${{ github.event.inputs.branch }}
  VERSION: ${{ github.event.inputs.version }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          token: ${{ secrets.PAT_TOKEN }}
     
      - name: Set python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

#      - name: Install dependencies
#        run: |
#            python -m pip install --upgrade pip
#            pip install setuptools wheel twine
            
#      - name: Make all and Packaging
#        run: |
#          make json
#          sudo chmod -R 777 dist
      
      - name: Push artifacts to origin master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: test/git
          commit_message: "[CI] api has been built"
          commit_user_name: ImmMin5
          commit_user_email: iam.minhokim@gmail.com
          commit_author: ImMin5 <mino@megazone.com>
          push_options: '--force'
          tagging_message: ${{ env.VERSION }}
        
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          src_path: dist/
          src_branch: test/git
          dst_branch: test/git
          dst_path: /.
          dst_owner: ImMin5
          dst_repo_name: api-doc
